# Generated by Django 4.1.13 on 2025-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=256)),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
